import { describe, expect, test } from "bun:test"
import { mkdtemp, readFile, rm } from "node:fs/promises"
import { join } from "node:path"
import { tmpdir } from "node:os"

const cliSource = join(import.meta.dir, "..", "src", "cli.ts")

async function runCli(args: string[]) {
  const proc = Bun.spawn([process.execPath, "run", "src/cli.ts", ...args], {
    cwd: join(import.meta.dir, ".."),
    stdout: "pipe",
    stderr: "pipe",
  })

  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ])

  return { stdout, stderr, exitCode }
}

describe("citty CLI", () => {
  test("keygen accepts a long --output option without treating it as a positional argument", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-cli-keygen-"))
    try {
      const result = await runCli(["keygen", "--output", dir])

      expect(result.exitCode).toBe(0)
      expect(result.stderr).toBe("")
      expect(result.stdout).toContain("Keypair generated.")
      expect(result.stdout).toContain(`Identity file:\n${join(dir, "identity.txt")}`)
      expect(result.stdout).toContain(`Recipient file:\n${join(dir, "recipient.txt")}`)
      expect(await readFile(join(dir, "identity.txt"), "utf8")).toContain("AGE-SECRET-KEY-")
      expect(await readFile(join(dir, "recipient.txt"), "utf8")).toContain("age1")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("help is generated by citty and lists the command tree", async () => {
    const result = await runCli(["--help"])

    expect(result.exitCode).toBe(0)
    expect(result.stdout).toContain("securebackup")
    expect(result.stdout).toContain("age-encrypted backup tool")
    expect(result.stdout).toContain("COMMANDS")
    expect(result.stdout).toContain("upload")
    expect(result.stdout).toContain("restore")
    expect(result.stdout).toContain("keygen")
  })

  test("help uses kebab-case flags consistently with error messages", async () => {
    const [encryptHelp, decryptHelp, uploadHelp] = await Promise.all([
      runCli(["encrypt", "--help"]),
      runCli(["decrypt", "--help"]),
      runCli(["upload", "--help"]),
    ])

    for (const result of [encryptHelp, decryptHelp, uploadHelp]) {
      expect(result.exitCode).toBe(0)
      expect(result.stderr).toBe("")
      expect(result.stdout).not.toContain("--outDir")
      expect(result.stdout).not.toContain("--chunksDir")
      expect(result.stdout).not.toContain("--chunkSize")
    }

    expect(encryptHelp.stdout).toContain("--out-dir=<chunks-dir>")
    expect(encryptHelp.stdout).toContain("--chunk-size=<size>")
    expect(decryptHelp.stdout).toContain("--chunks-dir=<dir>")
    expect(decryptHelp.stdout).toContain("--manifest=<manifest.json>")
    expect(uploadHelp.stdout).toContain("--chunk-size=<size>")
  })

  test("encrypt usage errors are shown without a stack trace", async () => {
    const result = await runCli(["encrypt", "example.txt"])

    expect(result.exitCode).toBe(1)
    expect(result.stdout).toBe("")
    expect(result.stderr).toContain("Error: encrypt requires either --output or --out-dir")
    expect(result.stderr).not.toContain("node_modules/citty")
    expect(result.stderr).not.toContain("src/cli.ts")
    expect(result.stderr).not.toContain(" at ")
  })

  test("all explicit CLI output goes through consola", async () => {
    const source = await readFile(cliSource, "utf8")

    expect(source).not.toContain("process.stdout.write")
    expect(source).not.toContain("process.stderr.write")
    expect(source).not.toContain("console.log")
    expect(source).not.toContain("console.error")
  })

  test("keygen reports existing key files without leaking filesystem stack traces", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-cli-keygen-existing-"))
    try {
      const first = await runCli(["keygen", "--output", dir])
      expect(first.exitCode).toBe(0)

      const second = await runCli(["keygen", "--output", dir])

      expect(second.exitCode).toBe(1)
      expect(second.stdout).toBe("")
      expect(second.stderr).toContain("Error: Key files already exist")
      expect(second.stderr).toContain(join(dir, "identity.txt"))
      expect(second.stderr).toContain(join(dir, "recipient.txt"))
      expect(second.stderr).not.toContain("EEXIST")
      expect(second.stderr).not.toContain("syscall")
      expect(second.stderr).not.toContain("src/commands/keygen.ts")
      expect(second.stderr).not.toContain(" at ")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })
})
