import { describe, expect, test } from "bun:test"
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { resolveRecipient, resolveIdentity, securebackupDir, recipientFilePath, identityFilePath } from "../src/core/resolver"

describe("key resolver", () => {
  test("returns flag value directly when provided", async () => {
    const r = await resolveRecipient("age1abc")
    expect(r).toBe("age1abc")

    const i = await resolveIdentity("AGE-SECRET-KEY-DEF")
    expect(i).toBe("AGE-SECRET-KEY-DEF")
  })

  test("reads recipient from ~/.securebackup/recipient.txt when flag is missing", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-resolver-"))
    try {
      await mkdir(join(dir, ".securebackup"), { recursive: true })
      await writeFile(join(dir, ".securebackup", "recipient.txt"), "# auto-generated by securebackup\nage1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p\n")
      
      const result = await resolveRecipient(undefined, dir)
      expect(result).toBe("age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("reads identity from ~/.securebackup/identity.txt when flag is missing", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-resolver-"))
    try {
      await mkdir(join(dir, ".securebackup"), { recursive: true })
      await writeFile(
        join(dir, ".securebackup", "identity.txt"),
        "# auto-generated by securebackup\n# public key: age1abc\nAGE-SECRET-KEY-1JYCZ5L0563XEMDEH69TLLWMK75L5A4PZ9A48L94TQSKYMENUJRUSXNPF6E\n",
      )
      
      const result = await resolveIdentity(undefined, dir)
      expect(result).toBe("AGE-SECRET-KEY-1JYCZ5L0563XEMDEH69TLLWMK75L5A4PZ9A48L94TQSKYMENUJRUSXNPF6E")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("throws when no flag and no file exists", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-resolver-"))
    try {
      await expect(resolveRecipient(undefined, dir)).rejects.toThrow("No --recipient given")
      await expect(resolveIdentity(undefined, dir)).rejects.toThrow("No --identity given")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("throws when file exists but no valid key line is found", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-resolver-"))
    try {
      await mkdir(join(dir, ".securebackup"), { recursive: true })
      await writeFile(join(dir, ".securebackup", "recipient.txt"), "# just a comment\n")
      await writeFile(join(dir, ".securebackup", "identity.txt"), "# just a comment\n")
      
      await expect(resolveRecipient(undefined, dir)).rejects.toThrow("No --recipient given")
      await expect(resolveIdentity(undefined, dir)).rejects.toThrow("No --identity given")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("path helpers return correct paths", () => {
    const dir = securebackupDir("/home/test")
    expect(dir).toBe("/home/test/.securebackup")
    expect(recipientFilePath("/home/test")).toBe("/home/test/.securebackup/recipient.txt")
    expect(identityFilePath("/home/test")).toBe("/home/test/.securebackup/identity.txt")
  })
})
