import { describe, expect, test } from "bun:test"
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { tmpdir } from "node:os"
import {
  resolveRecipient,
  resolveIdentity,
  securebackupDir,
  recipientFilePath,
  identityFilePath,
  readKeyFromFile,
} from "../src/core/resolver"

describe("key resolver", () => {
  test("reads recipient from explicit file path (SSH -i style)", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-resolver-"))
    try {
      await writeFile(
        join(dir, "my-recipient.txt"),
        "# my custom key\nage1abc123def456ghi\n",
      )
      const result = await resolveRecipient(join(dir, "my-recipient.txt"))
      expect(result).toBe("age1abc123def456ghi")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("reads identity from explicit file path (SSH -i style)", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-resolver-"))
    try {
      await writeFile(
        join(dir, "my-identity.txt"),
        "# auto-generated\nAGE-SECRET-KEY-ABCDEF1234567890\n",
      )
      const result = await resolveIdentity(join(dir, "my-identity.txt"))
      expect(result).toBe("AGE-SECRET-KEY-ABCDEF1234567890")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("reads recipient from ~/.securebackup/recipient.txt when flag is missing", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-resolver-"))
    try {
      await mkdir(join(dir, ".securebackup"), { recursive: true })
      await writeFile(join(dir, ".securebackup", "recipient.txt"), "# auto-generated by securebackup\nage1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p\n")
      
      const result = await resolveRecipient(undefined, dir)
      expect(result).toBe("age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("reads identity from ~/.securebackup/identity.txt when flag is missing", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-resolver-"))
    try {
      await mkdir(join(dir, ".securebackup"), { recursive: true })
      await writeFile(
        join(dir, ".securebackup", "identity.txt"),
        "# auto-generated by securebackup\n# public key: age1abc\nAGE-SECRET-KEY-1JYCZ5L0563XEMDEH69TLLWMK75L5A4PZ9A48L94TQSKYMENUJRUSXNPF6E\n",
      )
      
      const result = await resolveIdentity(undefined, dir)
      expect(result).toBe("AGE-SECRET-KEY-1JYCZ5L0563XEMDEH69TLLWMK75L5A4PZ9A48L94TQSKYMENUJRUSXNPF6E")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("throws when explicit file path has no valid key", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-resolver-"))
    try {
      await writeFile(join(dir, "bad.txt"), "# just a comment\n")
      await expect(resolveRecipient(join(dir, "bad.txt"))).rejects.toThrow("No age1... key found")
      await expect(resolveIdentity(join(dir, "bad.txt"))).rejects.toThrow("No AGE-SECRET-KEY-... found")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("throws when no flag and no file exists", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-resolver-"))
    try {
      await expect(resolveRecipient(undefined, dir)).rejects.toThrow("No --recipient given")
      await expect(resolveIdentity(undefined, dir)).rejects.toThrow("No --identity given")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("throws when file exists but no valid key line is found (fallback path)", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-resolver-"))
    try {
      await mkdir(join(dir, ".securebackup"), { recursive: true })
      await writeFile(join(dir, ".securebackup", "recipient.txt"), "# just a comment\n")
      await writeFile(join(dir, ".securebackup", "identity.txt"), "# just a comment\n")
      
      await expect(resolveRecipient(undefined, dir)).rejects.toThrow("No --recipient given")
      await expect(resolveIdentity(undefined, dir)).rejects.toThrow("No --identity given")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("readKeyFromFile extracts matching line", async () => {
    const dir = await mkdtemp(join(tmpdir(), "securebackup-resolver-"))
    try {
      await writeFile(join(dir, "keys.txt"), "# comment\nage1abc\nother\n")
      expect(await readKeyFromFile(join(dir, "keys.txt"), "age1")).toBe("age1abc")
      expect(await readKeyFromFile(join(dir, "keys.txt"), "AGE-SECRET-KEY-")).toBe("")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("path helpers return correct paths", () => {
    const dir = securebackupDir("/home/test")
    expect(dir).toBe("/home/test/.securebackup")
    expect(recipientFilePath("/home/test")).toBe("/home/test/.securebackup/recipient.txt")
    expect(identityFilePath("/home/test")).toBe("/home/test/.securebackup/identity.txt")
  })
})
