import * as age from "age-encryption"
import { access, chmod, mkdir, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { homedir } from "node:os"

export type GenerateKeypairOptions = {
  homeDir?: string
  outputDir?: string
}

export type GenerateKeypairResult = {
  keyDir: string
  identityFile: string
  recipientFile: string
  recipient: string
}

function timestamp(): string {
  return new Date().toISOString().replace(/\.\d{3}Z$/, "+00:00")
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

function existingKeyFilesError(identityFile: string, recipientFile: string): Error {
  return new Error(
    [
      "Key files already exist; refusing to overwrite them.",
      "",
      `Identity file: ${identityFile}`,
      `Recipient file: ${recipientFile}`,
      "",
      "Choose a different --output directory or move the existing key files first.",
    ].join("\n"),
  )
}

export async function generateKeypair(options: GenerateKeypairOptions = {}): Promise<GenerateKeypairResult> {
  const keyDir = options.outputDir ?? join(options.homeDir ?? homedir(), ".securebackup")
  const identityFile = join(keyDir, "identity.txt")
  const recipientFile = join(keyDir, "recipient.txt")

  await mkdir(keyDir, { recursive: true, mode: 0o700 })
  await chmod(keyDir, 0o700)

  if ((await exists(identityFile)) || (await exists(recipientFile))) {
    throw existingKeyFilesError(identityFile, recipientFile)
  }

  const identity = await age.generateIdentity()
  const recipient = await age.identityToRecipient(identity)

  const identityContent = [
    `# created: ${timestamp()}`,
    `# public key: ${recipient}`,
    "# auto-generated by securebackup. do not edit, commit, or paste this file anywhere.",
    "# this is your private key. if someone else gets it, they can decrypt your files.",
    identity,
    "",
  ].join("\n")

  const recipientContent = [
    `# created: ${timestamp()}`,
    "# auto-generated by securebackup. safe to share with anyone who needs to encrypt for you.",
    recipient,
    "",
  ].join("\n")

  await writeFile(identityFile, identityContent, { mode: 0o600, flag: "wx" })
  await chmod(identityFile, 0o600)
  await writeFile(recipientFile, recipientContent, { mode: 0o644, flag: "wx" })
  await chmod(recipientFile, 0o644)

  return { keyDir, identityFile, recipientFile, recipient }
}
